// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq20y_uC3ydnQk1u8Tg9jJjxD_Rfyy-ZA',
    appId: '1:706194743410:web:5f26fa414874d0f36aa2eb',
    messagingSenderId: '706194743410',
    projectId: 'taskly-t3',
    authDomain: 'taskly-t3.firebaseapp.com',
    storageBucket: 'taskly-t3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7RleaHRZwbEcwUnRYYbG2DvNGsa5B2j4',
    appId: '1:706194743410:android:0545d2b2459a88cc6aa2eb',
    messagingSenderId: '706194743410',
    projectId: 'taskly-t3',
    storageBucket: 'taskly-t3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWOBe3IVYVfGVqrHvVish5d_Yv4YJxmeo',
    appId: '1:706194743410:ios:ed23b4f0873bbc3d6aa2eb',
    messagingSenderId: '706194743410',
    projectId: 'taskly-t3',
    storageBucket: 'taskly-t3.firebasestorage.app',
    iosBundleId: 'com.example.taskly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWOBe3IVYVfGVqrHvVish5d_Yv4YJxmeo',
    appId: '1:706194743410:ios:ed23b4f0873bbc3d6aa2eb',
    messagingSenderId: '706194743410',
    projectId: 'taskly-t3',
    storageBucket: 'taskly-t3.firebasestorage.app',
    iosBundleId: 'com.example.taskly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq20y_uC3ydnQk1u8Tg9jJjxD_Rfyy-ZA',
    appId: '1:706194743410:web:f7a2ecf02e86a9926aa2eb',
    messagingSenderId: '706194743410',
    projectId: 'taskly-t3',
    authDomain: 'taskly-t3.firebaseapp.com',
    storageBucket: 'taskly-t3.firebasestorage.app',
  );
}
